[package]
edition = "2021"
license = "Apache-2.0"
name = "warpgate-protocol-kubernetes"
version = "0.14.1"

[dependencies]
anyhow = { version = "1.0", features = ["std"], default-features = false }
async-trait = { version = "0.1", default-features = false }
bytes.workspace = true
futures.workspace = true
kube.workspace = true
k8s-openapi.workspace = true
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = { version = "1.0", default-features = false }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid = { version = "1.3", features = ["v4"], default-features = false }
warpgate-common = { version = "*", path = "../warpgate-common", default-features = false }
warpgate-core = { version = "*", path = "../warpgate-core", default-features = false }
warpgate-db-entities = { version = "*", path = "../warpgate-db-entities", default-features = false }
poem.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
url = { version = "2.0", default-features = false }
http = { version = "1.0", default-features = false }
secrecy = { version = "0.10", default-features = false }
sea-orm.workspace = true
chrono = { version = "0.4", default-features = false, features = ["serde"] }
